expdir: ???
last_ckpt: null
run_valid: True
run_train: True
num_workers: 32

trainer:
  max_steps: 100000
  log_every_n_steps: 100
  val_check_interval: ${eval:'${trainer.accumulate_grad_batches} * ${checkpoint.valid_steps}'}
  check_val_every_n_epoch: null
  accumulate_grad_batches: 8
  accelerator: gpu
  devices: [0]

checkpoint:
  save_steps: 250
  valid_steps: 500
  valid_metric: valid/mse
  valid_higher_better: False

data:
  train:
    csv: data/split_9_1_seed0/train.csv
    data_dir: ../data/train_images
  valid:
    csv: data/split_9_1_seed0/valid.csv
    data_dir: ../data/train_images

dataloader:
  train:
    batch_size: 32
    shuffle: True
    num_workers: ${num_workers}
  valid:
    batch_size: 1
    shuffle: False
    num_workers: ${num_workers}

collater:
  upstream_name: ${model.upstream_name}

model:
  lr: 1.0e-4
  upstream_name: facebook/dinov2-base
